spring.application.name=padel_app

# MongoDB Atlas - substitueix amb la teva URI
spring.data.mongodb.uri=mongodb+srv://<usuari>:<contrasenya>@<cluster>.mongodb.net/padeldb?retryWrites=true&w=majority
spring.data.mongodb.database=padeldb

# JWT
jwt.secret=PadelHubSecretKeyMoltLlargaPerque256Bits1234!!
jwt.expiration-ms=86400000

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Servidor
server.port=8080
