spring.application.name=padel_app

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://padeladmin:3MWHizY0lSvZ6Sud@padel-cluster.ww8jhvm.mongodb.net/padeldb?retryWrites=true&w=majority
spring.data.mongodb.database=padeldb

# JWT
jwt.secret=PadelHubSecretKeyMoltLlargaPerque256Bits1234!!
jwt.expiration-ms=86400000

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Servidor
server.port=8080